version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordem-servico-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - ordem-net

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ordem-servico-api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=OrdemServicoDb;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - ordem-net

volumes:
  mssqldata:

networks:
  ordem-net:
    driver: bridge
